"$schema" = 'https://starship.rs/config-schema.json'

format = """
[@THEME_ICON@](fg:iris) \
$username\
$directory\
$git_branch\
$git_status\
$docker_context\
$nix_shell\
$fill\
$nodejs\
$java\
$rust\
$cmd_duration\
$time\n  \
$status\
[󱞪](fg:iris) \
"""

palette = "theme"

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay) "
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = '[](fg:overlay)([$all_status$ahead_behind]($style))[](fg:overlay) '
up_to_date = '[ ✓ ](bg:overlay fg:iris)'
untracked = '[?\($count\)](bg:overlay fg:gold)'
stashed = '[\$](bg:overlay fg:iris)'
modified = '[!\($count\)](bg:overlay fg:gold)'
renamed = '[»\($count\)](bg:overlay fg:iris)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:overlay fg:gold)'
ahead = '[⇡\(${count}\)](bg:overlay fg:foam)'
diverged = '⇕[\[](bg:overlay fg:iris)[⇡\(${ahead_count}\)](bg:overlay fg:foam)[⇣\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)'
behind = '[⇣\(${count}\)](bg:overlay fg:rose)'

[time]
disabled = false
format = " [](fg:overlay)[ $time 󰴈 ]($style)[](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

# Languages

[java]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = "󰎙 "

[rust]
style = "bg:overlay fg:pine"
format = " [](fg:overlay)[ $symbol$version ]($style)[](fg:overlay)"
disabled = false
symbol = " "

# Environment

[nix_shell]
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[ $symbol$state ]($style)[](fg:overlay) "
disabled = false
symbol = "❄ "

[docker_context]
style = "bg:overlay fg:foam"
format = "[](fg:overlay)[ $symbol$context ]($style)[](fg:overlay) "
disabled = false
symbol = "🐳 "
only_with_files = true

[cmd_duration]
style = "bg:overlay fg:gold"
format = "[](fg:overlay)[ ⏱ $duration ]($style)[](fg:overlay) "
disabled = false
min_time = 2000

[status]
style = "bg:overlay fg:love"
format = '[](fg:overlay)[ ✘ $status ]($style)[](fg:overlay) '
disabled = false
