"$schema" = 'https://starship.rs/config-schema.json'

format = """
[@THEME_ICON@](fg:accent) \
$username\
$directory\
$git_branch\
$git_status\
$docker_context\
$nix_shell\
$fill\
$nodejs\
$java\
$rust\
$cmd_duration\
$time\n  \
$status\
[󱞪](fg:accent) \
"""

palette = "theme"

[directory]
format = "[](fg:bg_select)[ $path ]($style)[](fg:bg_select) "
style = "bg:bg_select fg:blue"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:bg_select"
symbol = " "

[git_branch]
format = "[](fg:bg_select)[ $symbol $branch ]($style)[](fg:bg_select) "
style = "bg:bg_select fg:cyan"
symbol = ""

[git_status]
disabled = false
style = "bg:bg_select fg:error"
format = '[](fg:bg_select)([$all_status$ahead_behind]($style))[](fg:bg_select) '
up_to_date = '[ ✓ ](bg:bg_select fg:accent)'
untracked = '[?\($count\)](bg:bg_select fg:warning)'
stashed = '[\$](bg:bg_select fg:accent)'
modified = '[!\($count\)](bg:bg_select fg:warning)'
renamed = '[»\($count\)](bg:bg_select fg:accent)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:bg_select fg:warning)'
ahead = '[⇡\(${count}\)](bg:bg_select fg:cyan)'
diverged = '⇕[\[](bg:bg_select fg:accent)[⇡\(${ahead_count}\)](bg:bg_select fg:cyan)[⇣\(${behind_count}\)](bg:bg_select fg:accent2)[\]](bg:bg_select fg:accent)'
behind = '[⇣\(${count}\)](bg:bg_select fg:accent2)'

[time]
disabled = false
format = " [](fg:bg_select)[ $time 󰴈 ]($style)[](fg:bg_select)"
style = "bg:bg_select fg:accent2"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:bg_select)[ 󰧱 $user ]($style)[](fg:bg_select) "
show_always = true
style_root = "bg:bg_select fg:accent"
style_user = "bg:bg_select fg:accent"

# Languages

[java]
style = "bg:bg_select fg:blue"
format = " [](fg:bg_select)[ $symbol$version ]($style)[](fg:bg_select)"
disabled = false
symbol = " "

[nodejs]
style = "bg:bg_select fg:blue"
format = " [](fg:bg_select)[ $symbol$version ]($style)[](fg:bg_select)"
disabled = false
symbol = "󰎙 "

[rust]
style = "bg:bg_select fg:blue"
format = " [](fg:bg_select)[ $symbol$version ]($style)[](fg:bg_select)"
disabled = false
symbol = " "

# Environment

[nix_shell]
style = "bg:bg_select fg:cyan"
format = "[](fg:bg_select)[ $symbol$state ]($style)[](fg:bg_select) "
disabled = false
symbol = "❄ "

[docker_context]
style = "bg:bg_select fg:cyan"
format = "[](fg:bg_select)[ $symbol$context ]($style)[](fg:bg_select) "
disabled = false
symbol = "🐳 "
only_with_files = true

[cmd_duration]
style = "bg:bg_select fg:warning"
format = "[](fg:bg_select)[ ⏱ $duration ]($style)[](fg:bg_select) "
disabled = false
min_time = 2000

[status]
style = "bg:bg_select fg:error"
format = '[](fg:bg_select)[ ✘ $status ]($style)[](fg:bg_select) '
disabled = false
